version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000'
    depends_on:
      - todo-service

  todo-service:
    build: ./todo-service
    container_name: todo-service
    ports:
      - '4001:4001'
